### ISSUE TITLE
Request: Make this work with books that are in PDF format already

### ISSUE THREAD

**Issue by lvltoni** [evmer/perlego-downloader#1]
Hi, this seems great, but I believe that it only works with books that are in ePub format on Perlego. Is there any chance it could be expanded to include books that are in .pdf format already?

**Comment by evmer** [comment]
Hi, thank you for the interest.

I submitted the commit and PDF downloads are now supported. I apologise, the whole script is basically uncommented spaghetti code. But I added the first working implementation and it does the job. Maybe I'll refactor it later.

**Comment by lvltoni** [comment]
Thank you so much for your fast response, it works perfectly! Great work.

Might be worth mentioning in the readme that Debian/Ubuntu users will need the [static version of wkhtmltopdf ](https://wkhtmltopdf.org/downloads.html) rather than the lastest release!
