### ISSUE TITLE
uvloop does not support windows

### ISSUE THREAD

**Issue by jaan143** [evmer/perlego-downloader#10]
Collecting uvloop
  Using cached uvloop-0.16.0.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-8yu86g2k\uvloop_b8a859a0e28f49d49f1cf699eb8d3af0\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by evmer** [comment]
Thanks for reporting this to me. You're right and it isn't supported on Windows. https://github.com/MagicStack/uvloop/issues/14

I have removed uvloop.

**Comment by jaan143** [comment]
@evmer  did you fix image breaks issue in this new release ?

**Comment by evmer** [comment]
@jaan143 No, there isn't much I can do atm. Read my reply to https://github.com/evmer/perlego-downloader/issues/6#issuecomment-1242165538

**Comment by jaan143** [comment]
@evmer 
Dear you did not try to make script for Scribd ?
it have big library so please try to do that.
