### ISSUE TITLE
download error: Connection timed out"

### ISSUE THREAD

**Issue by lyyangyy** [evmer/perlego-downloader#11]
Hello again,

Sorry to bother you again. I tried running the script again and to no avail :(

It's giving me an error "download error: Connection timed out"

Thanks in advance for your assistance ! 
![Screen Shot 2022-09-18 at 11 56 21](https://user-images.githubusercontent.com/84595741/190886470-64365e2e-de55-4d4b-8de6-93e59660488c.jpg)

**Comment by evmer** [comment]
I'm afraid that it's a problem from your side, I was able to download your book without any issue:

<img width="1735" alt="image" src="https://user-images.githubusercontent.com/10036897/190924441-f097af5f-10e5-4bcd-a5a2-24ffa1dc2a7a.png">

Please check your internet connection & retry to run the script

**Comment by Moanrisy** [comment]
I have this problem too, @lyyangyy do you find solution?

**Comment by gnawretep** [comment]
#29 didn't answer the solution, and it's "read operation timed out", not "connection timed out"
