### ISSUE TITLE
Page UTF-8 encoding issue?

### ISSUE THREAD

**Issue by reallyallnamestaken** [evmer/perlego-downloader#13]
I would come across some books with what looks to be character encoding issues.
These would be seemingly random pages (though always the same pages if I redo the download) in only certain books.

characters such as â€¢Â or ÂÂÂ, etc will appear across these pages.

**Comment by reallyallnamestaken** [comment]
I found the issue to be due the we pages being UTF-8 encoded, but no header is set to let the browser know this.
As a workaround I modified the code to the needed header to the cache file.

```# save page in the cache dir
f = open(f'{cache_dir}/{chapter_no}.html', 'w', encoding='utf-8')
#below line does the magic
f.write('<meta charset="utf-8" />\n')
f.write(content)
f.close()
```

**Comment by evmer** [comment]
Hello, thank you for reporting this to me. I modified the script with your proposed fix.
