### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by abrahamsen911** [evmer/perlego-downloader#17]

**Comment by lorenzolangone** [comment]
I have the same problem

**Comment by lorenzolangone** [comment]
Ho did you manage it?

**Comment by evmer** [comment]
@lorenzolangone install the Python dependences:

```
  >$ pip3 install -r requirements.txt
```

Please read [the README](https://github.com/evmer/perlego-downloader#readme) for further info.

**Comment by lorenzolangone** [comment]
i've done and if i try agian it states "Requirement already satisfied"

**Comment by evmer** [comment]
@aimiiu can you please remove uvloop from requirements.txt and re-run that command?

**Comment by aimiiu** [comment]
> @aimiiu can you please remove uvloop from requirements.txt and re-run that command?

Thank you for your help!

I get the message "Requirement already satisfied" as I already tried this before. After this, when I run the downloader.py I get:

C:\Users\Ioana>python3 C:\Users\Ioana\Desktop\perlego\downloader.py
Traceback (most recent call last):
  File "C:\Users\Ioana\Desktop\perlego\downloader.py", line 2, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by evmer** [comment]
@aimiiu try `pip3 install Pillow`

**Comment by aimiiu** [comment]
> @aimiiu try `pip3 install Pillow`

C:\Users\Ioana>pip3 install Pillow
Collecting Pillow
  Downloading Pillow-9.2.0-cp310-cp310-win_amd64.whl (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 7.0 MB/s eta 0:00:00
Installing collected packages: Pillow
Successfully installed Pillow-9.2.0

C:\Users\Ioana>python3 C:\Users\Ioana\Desktop\perlego\downloader.py
Traceback (most recent call last):
  File "C:\Users\Ioana\Desktop\perlego\downloader.py", line 2, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by evmer** [comment]
@aimiiu please post here the output of `python3 -c "import Image"`

**Comment by aimiiu** [comment]
> @aimiiu please post here the output of `python3 -c "import Image"`

@evmer please refer below:

C:\Users\Ioana>python3 -c "import Image"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Image'

**Comment by evmer** [comment]
@aimiiu there must have been an issue during the installation of the python dependences.
1) uninstall Pillow with `pip3 uninstall Pillow`
2) upgrade pip with `python3 -m pip install --upgrade pip `
3) re-download `requirements.txt` from [here](https://github.com/evmer/perlego-downloader/blob/main/requirements.txt) (copy-paste)
4) re-install the python3 dependences: `pip3 install -r requirements.txt`
4) try to run downloader.py
