### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by Alexmonroeni** [evmer/perlego-downloader#19]
Traceback (most recent call last):
  File "/home/xxxxx/perlego-downloader/downloader.py", line 156, in <module>
    os.mkdir(cache_dir)
PermissionError: [Errno 13] Permission denied: '/home/xxxx/perlego-downloader/PDF_144322/'

**Comment by evmer** [comment]
Add write permissions to the script folder

**Comment by Alexmonroeni** [comment]
How do I do that? Sorry I’m very new to this, hope you can help me out :)

**Comment by evmer** [comment]
`chmod +w perlego-downloader `

**Comment by Alexmonroeni** [comment]
Thanks so much :)

**Comment by Alexmonroeni** [comment]
I tried giving it read and write permissions, and that fixed it, but now
its giving me this error after it finishes ripping the book.

Traceback (most recent call last):
  File "/home/amoxl/perlego-downloader/downloader.py", line 243, in <module>
    asyncio.run(html2pdf())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in
run_until_complete
    return future.result()
  File "/home/amoxl/perlego-downloader/downloader.py", line 164, in html2pdf
    browser = await launch(options={
  File
"/home/amoxl/.local/lib/python3.10/site-packages/pyppeteer/launcher.py",
line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File
"/home/amoxl/.local/lib/python3.10/site-packages/pyppeteer/launcher.py",
line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File
"/home/amoxl/.local/lib/python3.10/site-packages/pyppeteer/launcher.py",
line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by Alexmonroeni** [comment]
Can you help me fix it ? I would appreciate it, you seem like a hard
worker. :)
