### ISSUE TITLE
Unexpected TOKEN - Windows 7 - Error

### ISSUE THREAD

**Issue by sfoot13** [evmer/perlego-downloader#28]
Hello, first, thank you very much for this great tool.
Second, I'm having this error on Windows 7:

Símbolo (token) inesperado 'C:\\Users\\Mac\\AppData\\Local\\pyppeteer\\pyppeteer\\local-chromium\\588429\\chrome-win32\
\chrome.exe' en la expresión o la instrucción.
En línea: 1 Carácter: 914
+ 'C:\\Users\\Mac\\AppData\\Local\\pyppeteer\\pyppeteer\\local-chromium\\588429\\chrome-win32\\chrome.exe --disable-bac
kground-networking --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable
-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=
site-per-process --disable-hang-monitor --disable-popup-blocking--disable-prompt-on-repost --disable-sync --disable-tra
nslate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=
basic--use-mock-keychain --headless --hide-scrollbars --mute-audio --disable-gpu about:blank --remote-debugging-port=17
61 --user-data-dir=C:\\Users\\Mac\\AppData\\Local\\pyppeteer\\pyppeteer\\.dev_profile\\tmpa5fw9qio'C:\\Users\\Mac\\AppD
ata\\Local\\pyppeteer\\pyppeteer\\local-chromium\\588429\\chrome-win32\\chrome.exe <<<<  --disable-background-networkin
g --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable-client-side-phis
hing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process
--disable-hang-monitor --disable-popup-blocking--disable-prompt-on-repost --disable-sync --disable-translate --metrics-
recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic--use-mock-k
eychain --headless --hide-scrollbars --mute-audio --disable-gpu about:blank --remote-debugging-port=1761 --user-data-di
r=C:\\Users\\Mac\\AppData\\Local\\pyppeteer\\pyppeteer\\.dev_profile\\tmpa5fw9qio
    + CategoryInfo          : ParserError: (C:\\Users\\Mac\...n32\\chrome.exe:String) [], ParentContainsErrorRecordExc
   eption
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\python\python38>

Could you help me please?
Thanks in advanced.

**Comment by evmer** [comment]
Hello, chrome is missing from your local system. Run `pyppeteer-install` command and then restart the script.

**Comment by sfoot13** [comment]
> Hello, chrome is missing from your local system. Run `pyppeteer-install` command and then restart the script.

Hello Evmer :smiley: :
After many tries, finally it worked! But I had to install Ubuntu on my notebook, was really easier with Linux, all the necessary files installed correctly.

I have just one question, the final PDF has very narrow margins, is it possible to change the dimension's margins?

Thank you very much for this incredible script!
Thank you very much and have a good day :smiley: 
![Captura de pantalla_2022-11-18_23-29-52](https://user-images.githubusercontent.com/26035719/202830333-b5c14c3d-9061-4d7e-bab0-86d8cbc99887.jpg)

**Comment by evmer** [comment]
Hey @sfoot13, glad to hear you managed to make it working. I'm sorry but I'm not been able to test on Windows yet so I can't handle the related issues right now.

Regarding the document settings (margins, page size, spacing etc.) you can look at lines 232-239 and refer to the pyppeteer's [page.pdf() documentation](https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.page.Page.pdf) (see under options).

<img width="772" alt="image" src="https://user-images.githubusercontent.com/10036897/205085894-8f9b55d2-1a7e-4f45-8af5-dec22f553c78.png">
