### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jaan143** [evmer/perlego-downloader#3]
hello
i am getting this error dear

building pdf...
Traceback (most recent call last):
  File "downloader.py", line 141, in <module>
    f.write(content)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ue000' in position 15534: character maps to <undefined>

**Comment by evmer** [comment]
Hello, can you please post the book url/id so I can investigate the issue? Thank you.

**Comment by a-sinclaire** [comment]
I also ran into this same (or a similar) issue...

```
building pdf...
Traceback (most recent call last):
File "C:\Users\HP\Downloads\perlego-downloader-main\perlego-downloader-main\downloader.py", line 141, in <module>
    f.write(content)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2003' in position 1965: character maps to <undefined>
```

What I suspect is going on is when we open the file (one line earlier line 140) it is creating a file with a format which cannot support certain encoded characters.

I fixed this issue for me by altering line 140 to create the file with encoding 'utf-8'
`f = open(f'epub_{BOOK_ID}/{page_no}.html', 'w', encoding='utf-8')`

**Comment by jaan143** [comment]
@evmer  i tried same your book also this one 
https://www.perlego.com/book/2173908/good-work-how-to-build-a-career-that-makes-a-difference-in-the-world-pdf

i tried both books which you showed in tutorial but getting same error

**Comment by jaan143** [comment]
@a-sinclaire i replaced your given line in line 140 but now i am getting this error
building pdf...
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\configuration.py", line 35, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader.py", line 146, in <module>
    pdfkit.from_file([f'epub_{BOOK_ID}/{i}.html' for i in range(page_no)], f'{BOOK_ID}.pdf', options={'encoding': 'UTF-8'})
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\api.py", line 48, in from_file
    r = PDFKit(input, 'file', options=options, toc=toc, cover=cover, css=css,
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\pdfkit.py", line 45, in __init__
    self.configuration = (Configuration() if configuration is None
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\configuration.py", line 38, in __init__
    raise IOError('No wkhtmltopdf executable found: "%s"\n'
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it or you can pass path to it manually in method call, check README. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
PS C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main>

**Comment by evmer** [comment]
Thanks @a-sinclaire for the contribution. I'll do some tests and create a pull request to update the script.

@jaan143 the script cannot find the wkhtmltopdf executable, make sure you have it installed.
Also, you can give the script the full path of the executable:

```
path_wkhtmltopdf = "C:\Program Files(x86)\wkhtmltopdf\bin\wkhtmltopdf.exe"
config = pdfkit.configuration(wkhtmltopdf = path_wkhtmltopdf)
pdfkit.from_file([f'epub_{BOOK_ID}/{i}.html' for i in range(page_no)], f'{BOOK_ID}.pdf', options={'encoding': 'UTF-8'}, configuration = config)
```

**Comment by jaan143** [comment]
@evmer  images are missing from pdf 
this one i tried 
https://www.perlego.com/book/3290633/environment-and-society-a-critical-introduction-pdf

**Comment by evmer** [comment]
@jaan143 thanks for reporting this to me. Now I should have fixed the issue. Not sure if it's the perfect solution, but for now it does the job. let me know!

**Comment by jaan143** [comment]
@evmer  thanks dear and what about the missing chapter issue ?
https://www.perlego.com/book/2568251/english-rhythm-and-blues-where-language-and-music-come-together-pdf
