### ISSUE TITLE
Issue on Windows 10

### ISSUE THREAD

**Issue by herovax** [evmer/perlego-downloader#30]
I received a message that says "perlego-downloader-main\downloader.py", line 2, in <module> from PIL import Image ModuleNotFoundError: No module named 'PIL'". I'm not sure which step did I do wrong.

**Comment by evmer** [comment]
Hello, do you have installed the Python requirements with `pip3 install -r requirements.txt`?

**Comment by herovax** [comment]
Yes, it has successfully installed the entire list. Somehow the error starts at line 2. What module is that? Maybe I can reinstall that part.

**Comment by evmer** [comment]
Try `pip install pillow`

**Comment by evmer** [comment]
I suppose this issue has been fixed installing the right dependences. I'm closing this issue, feel free to reopen it
