### ISSUE TITLE
Issues: CERTIFICATE VERIFY FAILED

### ISSUE THREAD

**Issue by bleedingsaber** [evmer/perlego-downloader#33]
After running the script, error shows below:

init_book_delivery() error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

I am sure I am copy and past correctly.

**Comment by evmer** [comment]
Hey, thank you for reporting me this.

I disabled the SSL verification, can you please re-download the script and retry? Thank you!

**Comment by bleedingsaber** [comment]
Yeah, it's working now. Thanks for your help.
