### ISSUE TITLE
KeyError: 'event' line 70, in <module>

### ISSUE THREAD

**Issue by Faisalnd** [evmer/perlego-downloader#35]
Greetings everyone,

I've update the last files, yet I've an issue 
hope you can help 

with the following

% python3 downloader.py 
chapters 0-1 downloaded
chapters 1-2 downloaded
chapters 2-3 downloaded
chapters 3-4 downloaded
chapters 4-5 downloaded
chapters 5-22 downloaded
chapters 22-34 downloaded
chapters 34-48 downloaded
chapters 48-49 downloaded
Traceback (most recent call last):
  File "/Users/user/perlego/downloader.py", line 70, in <module>
    if data['event'] == 'error':
KeyError: 'event'

**Comment by evmer** [comment]
I'm not able to replicate this issue, have you already tried to re-run the script?

**Comment by rassoulamar** [comment]
hello i have the same problem on macos motenery

**Comment by rassoulamar** [comment]
try to download this book https://ereader.perlego.com/1/book/3420900
