### ISSUE TITLE
what to do?

### ISSUE THREAD

**Issue by rahulbanwasi** [evmer/perlego-downloader#37]
OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail

**Comment by rahulbanwasi** [comment]
in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by evmer** [comment]
Duplicate of #9
