### ISSUE TITLE
websocket expception error

### ISSUE THREAD

**Issue by smack893** [evmer/perlego-downloader#6]
![image](https://user-images.githubusercontent.com/64412656/189265144-77447ecf-2740-4db6-b878-98db46ee98f0.png)

**Comment by smack893** [comment]
![image](https://user-images.githubusercontent.com/64412656/189266223-7906491e-dc44-4fc3-95c7-624edb5c2565.png)
same issue in linux

**Comment by evmer** [comment]
Hello, can you please share the BOOK_ID so I can investigate the issue?

**Comment by smack893** [comment]
> Hello, can you please share the BOOK_ID so I can investigate the issue?

Book ID: 1425905
also found another issue see the below image it cut down page and show complete empty page
![image](https://user-images.githubusercontent.com/64412656/189371748-32a53784-15c5-4da3-88a6-03e84aea6201.png)

**Comment by evmer** [comment]
@smack893 

Regarding the first issue ("Illegal frame"), I'll replace the websocket library with a more stable one. In the meanwhile, you can just restart the script and it'll be fine.

Unfortunately there's not much we can do to fix the wrong page splitting bug. The original book format is EPUB (= infinite content size) and the output is a PDF document, so the original content is split into multiple pages with a fixed (arbitrary) height that may not fit with the content.

**Comment by evmer** [comment]
This bug is now fixed. If a 'Illegal frame' is received, the script will try to reconnect to websocket and resume the download.
