### ISSUE TITLE
Connection to remote host was lost?

### ISSUE THREAD

**Issue by lyyangyy** [evmer/perlego-downloader#7]
Hi all!

Sorry, i'm relatively new to all these coding, so hopefully it's an easy fix for someone out there. I followed the instructions as per your video, however I'm receiving  the following error: 

"websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost."

Any help would be appreciated. Thanks in advance 

![Screen Shot 2022-09-11 at 23 49 37](https://user-images.githubusercontent.com/84595741/189539477-5dd88cf9-9441-498b-9d17-d84e4bdc4920.jpg)

**Comment by evmer** [comment]
Hello!

Unfortunately it's a known issue, see #6. The websocket library is unstable and connection exceptions are not properly handled. I plan to refactor the script, so please have patience. For now, you can try to restart the script and hopefully it'll be fine.

**Comment by lyyangyy** [comment]
Thanks 

> Hello!
> 
> Unfortunately it's a known issue, see #6. The websocket library is unstable and connection exceptions are not properly handled. I plan to refactor the script, so please have patience. For now, you can try to restart the script and hopefully it'll be fine.

Thanks a lot for the prompt reply. You're doing gods work :D 

I wish I could help, but this is all new to me :(

**Comment by lyyangyy** [comment]
> Hello!
> 
> Unfortunately it's a known issue, see #6. The websocket library is unstable and connection exceptions are not properly handled. I plan to refactor the script, so please have patience. For now, you can try to restart the script and hopefully it'll be fine.

Thanks a lot for the prompt reply. You're doing gods work :D

I wish I could be of more assistance, but this is all new to me :( Thanks again!

**Comment by evmer** [comment]
The bug is now fixed. If the websocket connection is lost, the script will try to reconnect and resume the download:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/10036897/189639222-54d147f3-0924-4a84-8874-7c464ea5d360.png">
