### ISSUE TITLE
I need a help :)

### ISSUE THREAD

**Issue by Lacittadavanguardia** [evmer/perlego-downloader#74]
Hi, 
first of all thank you very much for writing the code!

I found authToken, bookId and reCaptchaToken and pasted it, but somehow it's not working.
I am using Python for the first time and Termainal for the 2 or third time and cannot understand what I am doing wrong...
Could you please advise me? Many many thanks in advance!!
<img width="567" alt="Screenshot 2023-07-14 at 08 07 20" src="https://github.com/evmer/perlego-downloader/assets/139532174/a280c652-74c9-41ef-a7f7-b76b913ca447">
<img width="570" alt="Screenshot 2023-07-14 at 08 12 25" src="https://github.com/evmer/perlego-downloader/assets/139532174/e84c06f1-7a53-435f-8ba9-fcd0c3f9ff47">

**Comment by codebreakeranddestroyer** [comment]
This code is no longer working

**Comment by rahulbanwasi** [comment]
any update?

**Comment by Lacittadavanguardia** [comment]
> any update?

nope. no updates, no replies, no comments, and this code is not working (at least for me)

**Comment by masteoo** [comment]
> > any update?
> 
> nope. no updates, no replies, no comments, and this code is not working (at least for me)

@Lacittadavanguardia hello, do you have an active Perlego account? write me also on Telegram if you want @ProseccoDoc
